---
name: Validation
permissions:
  actions: read
  contents: write
  pull-requests: read
  security-events: write
"on":
  pull_request:
    branches:
    - develop
    - main
  push:
    branches:
    - develop
    - main
  workflow_dispatch: null
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref\
    \ }}"
  cancel-in-progress: true
jobs:
  build-and-quality-scans:
    env:
      IMAGE_NAME: ob-innovation/employer-details-api
      DOCKER_REPOSITORY: docker.repo1.uhc.com
      JAVA_VERSION: 21
      MAVEN_VERSION: 3.9.6
    runs-on: uhg-runner
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Determine the PR build version suffix
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' &&
        github.event_name == 'pull_request'
      id: pr-build-suffix
      run: |
        set -e

        suffix=""

        echo "Detected PR build, calculating suffix..."
        echo "PR Number: ${PR_NUMBER}"
        echo "Run Number: ${RUN_NUMBER}"
        echo "Run Attempt: ${RUN_ATTEMPT}"
        suffix="PR-${PR_NUMBER}_${RUN_NUMBER}-${RUN_ATTEMPT}"
        echo "suffix=$suffix"
        echo "suffix=$suffix" >> "$GITHUB_OUTPUT"
        echo "TAG=$suffix" >> "$GITHUB_ENV"
      env:
        SHA: "${{ github.sha }}"
        RUN_ATTEMPT: "${{ github.run_attempt }}"
        RUN_NUMBER: "${{ github.run_number }}"
        PR_NUMBER: "${{ github.event.number }}"
    - name: Determine the branch build version suffix
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      id: branch-build-suffix
      run: |
        set -e

        suffix="develop"
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          suffix="main"
        fi

        echo "Detected branch build, calculating suffix..."
        echo "Run Number: ${RUN_NUMBER}"
        echo "Run Attempt: ${RUN_ATTEMPT}"
        suffix="${suffix}-${RUN_NUMBER}-${RUN_ATTEMPT}"
        echo "suffix=$suffix"
        echo "suffix=$suffix" >> "$GITHUB_OUTPUT"
        echo "TAG=$suffix" >> "$GITHUB_ENV"
      env:
        SHA: "${{ github.sha }}"
        RUN_ATTEMPT: "${{ github.run_attempt }}"
        RUN_NUMBER: "${{ github.run_number }}"
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: "${{ env.JAVA_VERSION }}"
        overwrite-settings: false
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: "${{ env.MAVEN_VERSION }}"
    - name: Maven Build and Quality Scan
      uses: optum-eeps/epl-actions/maven-build-scan@v1.27.4
      with:
        java-version: "${{ env.JAVA_VERSION }}"
        maven-version: "${{ env.MAVEN_VERSION }}"
        enable-codeql: false
    - name: Docker Build and Scan
      if: "${{ ! startsWith(github.head_ref, 'dependabot/') }}"
      uses: optum-eeps/epl-actions/docker-build-push@v1.27.4
      with:
        ask-id: UHGWM110-005677
        docker-push: true
        docker-image: "${{ env.IMAGE_NAME }}"
        docker-tag: "${{ env.TAG }}"
        docker-repository: "${{ env.DOCKER_REPOSITORY }}"
        registry-token: "${{ secrets.REGISTRY_TOKEN }}"
        registry-user: "${{ secrets.REGISTRY_USER }}"
        score: 8.0
        enable-xray: true
        enable-twistcli: false
        upload-sarif: true
    - name: Twistlock Scan
      if: "${{ ! startsWith(github.head_ref, 'dependabot/') }}"
      uses: optum-eeps/epl-actions/twistcli@v1.27.4
      with:
        prisma-user: "${{ secrets.TWISTCLI_USER }}"
        password: "${{ secrets.TWISTCLI_PASSWORD }}"
        image: "${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
        vulnerability-threshold: high
      continue-on-error: false
